export const __EmoteDian = [
    { key: "gif.1.gif", name: "挨打", width: 100, height: 100, display: "dian" },
    { key: "gif.2.gif", name: "戳瞎", width: 100, height: 100, display: "dian" },
    { key: "gif.3.gif", name: "奋斗", width: 100, height: 100, display: "dian" },
    { key: "gif.4.gif", name: "惊悚", width: 100, height: 100, display: "dian" },
    { key: "gif.5.gif", name: "囧", width: 100, height: 100, display: "dian" },
    { key: "gif.6.gif", name: "看书", width: 100, height: 100, display: "dian" },
    { key: "gif.7.gif", name: "哭哭", width: 100, height: 100, display: "dian" },
    { key: "gif.8.gif", name: "酷炫", width: 100, height: 100, display: "dian" },
    { key: "gif.9.gif", name: "困", width: 100, height: 100, display: "dian" },
    { key: "gif.10.gif", name: "路过", width: 100, height: 100, display: "dian" },
    { key: "gif.11.gif", name: "萌萌哒", width: 100, height: 100, display: "dian" },
    { key: "gif.12.gif", name: "亲吻", width: 100, height: 100, display: "dian" },
    { key: "gif.13.gif", name: "桑心", width: 100, height: 100, display: "dian" },
    { key: "gif.14.gif", name: "吐", width: 100, height: 100, display: "dian" },
    { key: "gif.15.gif", name: "无辜", width: 100, height: 100, display: "dian" },
    { key: "gif.16.gif", name: "夏天", width: 100, height: 100, display: "dian" },
    { key: "gif.17.gif", name: "摇摆", width: 100, height: 100, display: "dian" },
    { key: "gif.18.gif", name: "疑问", width: 100, height: 100, display: "dian" },
    { key: "gif.19.gif", name: "震惊", width: 100, height: 100, display: "dian" },
    { key: "gif.20.gif", name: "中箭", width: 100, height: 100, display: "dian" },
    { key: "gif.21.gif", name: "抓狂", width: 100, height: 100, display: "dian" }
];

export const __EmoteTan = [
    { key: "dan.1.gif", width: 200, height: 40, name: "666", display: "tan" },
    { key: "dan.2.gif", width: 200, height: 40, name: "2333", display: "tan" },
    { key: "dan.3.gif", width: 300, height: 40, name: "啊啊啊", display: "tan" },
    { key: "dan.4.gif", width: 300, height: 40, name: "哈哈哈", display: "tan" },
    { key: "dan.5.gif", width: 300, height: 40, name: "红红火火", display: "tan" },
    { key: "dan.6.gif", width: 200, height: 40, name: "雾草", display: "tan" },
    { key: "dan.7.gif", width: 200, height: 40, name: "呸呸呸", display: "tan" },
    { key: "dan.8.gif", width: 300, height: 40, name: "互相伤害", display: "tan" },
    { key: "dan.9.gif", width: 300, height: 40, name: "人呢", display: "tan" },
    { key: "dan.10.gif", width: 300, height: 40, name: "敢答应吗", display: "tan" },
    { key: "dan.11.gif", width: 300, height: 40, name: "警察蜀黍", display: "tan" },
    { key: "dan.12.gif", width: 200, height: 40, name: "污", display: "tan" },
    { key: "dan.13.gif", width: 400, height: 40, name: "不说扔狗", display: "tan" },
    { key: "dan.14.gif", width: 200, height: 40, name: "一起play", display: "tan" },
    { key: "dan.15.gif", width: 200, height: 40, name: "嘤嘤嘤", display: "tan" },
    { key: "dan.16.gif", width: 400, height: 40, name: "不明觉厉", display: "tan" },
    { key: "dan.17.gif", width: 200, height: 40, name: "妖妖灵吗", display: "tan" },
    { key: "dan.18.gif", width: 200, height: 40, name: "被掏空", display: "tan" },
    { key: "dan.19.gif", width: 300, height: 40, name: "我不听", display: "tan" },
    { key: "dan.20.gif", width: 200, height: 40, name: "辣眼睛", display: "tan" },
    { key: "dan.21.gif", width: 200, height: 40, name: "高能预警", display: "tan" },
    { key: "dan.22.gif", width: 200, height: 40, name: "静静看", display: "tan" },
    { key: "dan.23.gif", width: 200, height: 40, name: "ok", display: "tan" },
    { key: "dan.24.gif", width: 200, height: 40, name: "好", display: "tan" },
    { key: "dan.25.gif", width: 200, height: 40, name: "我很惆怅", display: "tan" },
    { key: "dan.26.gif", width: 200, height: 40, name: "引起注意", display: "tan" },
    { key: "dan.27.gif", width: 200, height: 40, name: "呵呵", display: "tan" },
    { key: "dan.28.gif", width: 200, height: 40, name: "老司机", display: "tan" },
    { key: "dan.29.gif", width: 300, height: 40, name: "我报警了", display: "tan" },
    { key: "dan.30.gif", width: 400, height: 40, name: "你无情", display: "tan" },
    { key: "dan.31.gif", width: 400, height: 40, name: "我好看", display: "tan" },
    { key: "dan.32.gif", width: 300, height: 40, name: "还能说啥", display: "tan" }
];

export const __EmoteMagic = [
    { name: "卡哇伊", key: "magic.1memoj_cute.png", width: 100, height: 100, display: "magic" },
    { name: "呵呵", key: "magic.2memoj_smile.png", width: 100, height: 100, display: "magic" },
    {
        name: "哭笑不得",
        key: "magic.3memoj_dumbfounding.png",
        width: 100,
        height: 100,
        display: "magic"
    },
    {
        name: "狂汗",
        key: "magic.4memoj_perspiration.png",
        width: 100,
        height: 100,
        display: "magic"
    },
    { name: "哭泣", key: "magic.5memoj_cry.png", width: 100, height: 100, display: "magic" },
    { name: "馋", key: "magic.6memoj_greed.png", width: 100, height: 100, display: "magic" },
    { name: "疑问", key: "magic.7memoj_question.png", width: 100, height: 100, display: "magic" },
    { name: "可怜", key: "magic.8memoj_pity.png", width: 100, height: 100, display: "magic" },
    { name: "猖狂笑", key: "magic.9memoj_laugh.png", width: 100, height: 100, display: "magic" },
    { name: "羞羞", key: "magic.10memoj_shy.png", width: 100, height: 100, display: "magic" },
    { name: "亲吻", key: "magic.11memoj_kiss.png", width: 100, height: 100, display: "magic" },
    { name: "乌鸦", key: "magic.12memoj_wuya.png", width: 100, height: 100, display: "magic" },
    { name: "呆", key: "magic.13memoj_asleep.png", width: 100, height: 100, display: "magic" },
    { name: "愤怒", key: "magic.14memoj_angry.png", width: 100, height: 100, display: "magic" },
    { name: "鄙视", key: "magic.15memoj_roar.png", width: 100, height: 100, display: "magic" },
    { name: "拜拜", key: "magic.16memoj_bye.png", width: 100, height: 100, display: "magic" },
    { name: "捂眼", key: "magic.17memoj_covereyes.png", width: 100, height: 100, display: "magic" },
    { name: "尴尬", key: "magic.18memoj_awkward.png", width: 100, height: 100, display: "magic" },
    { name: "大便", key: "magic.19memoj_excrment.png", width: 100, height: 100, display: "magic" },
    { name: "加油", key: "magic.20memoj_fighting.png", width: 100, height: 100, display: "magic" },
    { name: "早上好", key: "magic.21memoj_morning.png", width: 100, height: 100, display: "magic" },
    { name: "撇嘴", key: "magic.22memoj_curllips.png", width: 100, height: 100, display: "magic" },
    { name: "鄙视", key: "magic.23memoj_contempt.png", width: 100, height: 100, display: "magic" },
    { name: "委屈", key: "magic.24memoj_chagrin.png", width: 100, height: 100, display: "magic" },
    { name: "抠鼻", key: "magic.25memoj_digNose.png", width: 100, height: 100, display: "magic" },
    { name: "白眼", key: "magic.26memoj_rolleye.png", width: 100, height: 100, display: "magic" },
    { name: "OMG", key: "magic.27memoj_crazy.png", width: 100, height: 100, display: "magic" },
    { name: "晚安", key: "magic.28memoj_goodnight.png", width: 100, height: 100, display: "magic" },
    {
        name: "心碎",
        key: "magic.29memoj_heartBroken.png",
        width: 100,
        height: 100,
        display: "magic"
    },
    { name: "咒骂", key: "magic.30memoj_curse.png", width: 100, height: 100, display: "magic" },
    { name: "斜眼", key: "magic.31memoj_squint.png", width: 100, height: 100, display: "magic" },
    { name: "惊吓", key: "magic.32memoj_frighten.png", width: 100, height: 100, display: "magic" },
    { name: "暴走", key: "magic.33memoj_getup.png", width: 100, height: 100, display: "magic" },
    { name: "坏笑", key: "magic.34memoj_hinhin.png", width: 100, height: 100, display: "magic" },
    { name: "偷笑", key: "magic.35memoj_titter.png", width: 100, height: 100, display: "magic" },
    { name: "哼", key: "magic.36memoj_heng.png", width: 100, height: 100, display: "magic" },
    { name: "花痴", key: "magic.37memoj_love.png", width: 100, height: 100, display: "magic" },
    { name: "抱抱", key: "magic.38memoj_hug.png", width: 100, height: 100, display: "magic" },
    { name: "抓狂", key: "magic.39memoj_mad.png", width: 100, height: 100, display: "magic" },
    { name: "OK", key: "magic.40memoj_ok.png", width: 100, height: 100, display: "magic" },
    {
        name: "你逗我吗",
        key: "magic.41memoj_areYouFunny.png",
        width: 100,
        height: 100,
        display: "magic"
    },
    { name: "吐血", key: "magic.42memoj_penpen.png", width: 100, height: 100, display: "magic" },
    {
        name: "吐舌头",
        key: "magic.43memoj_showTongue.png",
        width: 100,
        height: 100,
        display: "magic"
    },
    { name: "赞美", key: "magic.44memoj_praise.png", width: 100, height: 100, display: "magic" },
    { name: "酷", key: "magic.45memoj_smoking.png", width: 100, height: 100, display: "magic" },
    { name: "熟睡", key: "magic.46memoj_sleep.png", width: 100, height: 100, display: "magic" },
    { name: "闭嘴", key: "magic.47memoj_shutup.png", width: 100, height: 100, display: "magic" },
    { name: "衰", key: "magic.48memoj_unlucky.png", width: 100, height: 100, display: "magic" }
];

export const __EmoteNormal = [
    { key: "emoji.a1.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.a2.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.a3.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.a4.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.a5.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.a6.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.a7.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.a8.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.a9.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.a10.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.b1.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.b2.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.b3.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.b4.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.b5.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.b6.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.b7.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.b8.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.b9.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.c1.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.c2.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.c3.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.c4.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.c5.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.c6.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.c7.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.c8.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.c9.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.c10.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.c11.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.d1.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.d2.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.d3.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.d4.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.d5.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.d6.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.e1.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.e2.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.e3.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.f1.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.f2.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.f3.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.f4.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.f5.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.f6.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g1.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g2.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g3.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g4.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g5.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g6.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g7.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g8.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g9.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g10.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g11.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g12.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g13.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g14.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g15.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g16.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g17.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g18.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g19.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.g20.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.h1.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.h2.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.h3.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.h4.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.h5.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.h6.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.h7.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.h8.png", width: 36, height: 36, display: "normal" },
    // { key: "emoji.h9.png", width: 36, height: 36, display: "normal" },
    // { key: "emoji.h10.png", width: 36, height: 36, display: "normal" },
    // { key: "emoji.h11.png", width: 36, height: 36, display: "normal" },
    // { key: "emoji.h12.png", width: 36, height: 36, display: "normal" },
    // { key: "emoji.h13.png", width: 36, height: 36, display: "normal" },
    // { key: "emoji.h14.png", width: 36, height: 36, display: "normal" },
    // { key: "emoji.h15.png", width: 36, height: 36, display: "normal" },
    // { key: "emoji.h16.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.h17.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i1.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i2.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i3.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i4.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i5.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i6.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i7.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i8.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i9.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i10.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i11.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i12.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i13.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i14.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i15.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i16.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i17.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i18.png", width: 36, height: 36, display: "normal" },
    // { key: "emoji.i19.png", width: 36, height: 36, display: "normal" },
    // { key: "emoji.i20.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i21.png", width: 36, height: 36, display: "normal" },
    // { key: "emoji.i22.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i23.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i24.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i25.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i26.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i27.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.i28.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j1.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j2.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j3.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j4.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j5.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j6.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j7.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j8.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j9.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j10.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j11.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j12.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j13.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j14.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j15.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j16.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j17.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j18.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j19.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j20.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j21.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j22.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j23.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j24.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j25.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j26.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j27.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j28.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j29.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j30.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.j31.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l1.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l2.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l3.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l4.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l5.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l6.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l7.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l8.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l9.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l10.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l11.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l12.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l13.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l14.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l15.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l16.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l17.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l18.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l19.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l20.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l21.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l22.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.l23.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.m1.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.m2.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.m3.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.m4.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.m5.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.m6.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.m7.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.n1.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.n2.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.n3.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.n4.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.n5.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.n6.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.n7.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.n8.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.n9.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.n10.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.n11.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.n12.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.n13.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.n14.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.n15.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.n16.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.n17.png", width: 36, height: 36, display: "normal" },
    { key: "emoji.n18.png", width: 36, height: 36, display: "normal" }
];

export const emojiData = [
    { label: "表情", value: __EmoteNormal },
    { label: "点点", value: __EmoteDian },
    { label: "弹弹", value: __EmoteTan },
    { label: "魔法", value: __EmoteMagic }
];
